retrieve-sources_task:
  container:
    image: ubuntu:20.04
  download_script: |
    apt-get update && apt-get install --no-install-recommends -y ca-certificates curl git
    export PATH=/usr/bin:$PATH
    ./actions/download.sh
    mkdir sources
    mv *tar.gz sources
  sources_cache:
    folder: sources
    fingerprint_key: sources

build-and-package_task:
  depends_on:
    - retrieve-sources
  arm_container:
    matrix:
      - image: alpine:3.12
      - image: alpine:3.13
      - image: alpine:3.14
      - image: alpine:3.15
      - image: alpine:edge
      - image: registry.access.redhat.com/ubi7-minimal
      - image: registry.access.redhat.com/ubi8-minimal
      - image: debian:9-slim
      - image: debian:10-slim
      - image: debian:11-slim
      - image: debian:testing-slim
      - image: fedora:34
      - image: fedora:35
      - image: fedora:rawhide
      - image: opensuse/leap:15.3
      - image: opensuse/tumbleweed
      - image: ubuntu:16.04
      - image: ubuntu:18.04
      - image: ubuntu:20.04
      - image: ubuntu:21.04
      - image: ubuntu:21.10
      - image: ubuntu:devel
  timeout_in: 120m
  buildenv_script: |
    chmod +x actions/*
    . actions/buildenv.sh
  retrievesources_script: |
    set -xv
    ls -la
    curl -v http://$CIRRUS_HTTP_CACHE_HOST/sources
    ls -la
    tar xvzf sources.tar.gz
  build_script: ./actions/build.sh
  package_script: |
    ./actions/package.sh
    ls -lh packages  
